---
- name: Include monitoring tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/monitoring.yaml"
  when: skip_monitoring == false

- name: Include Sui tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/sui.yaml"