---
- name: Add a sui user
  ansible.builtin.user:
    name: sui
    shell: /bin/bash

- name: Create sui directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "sui"
    group: "sui"
    mode: 0755
  loop:
    - /opt/sui/bin
    - /opt/sui/config
    - /opt/sui/db
    - /opt/sui/key-pairs

- name: Copy validator configuration file
  template:
    src: validator.yaml.j2
    dest: /opt/sui/config/validator.yaml
    owner: "sui"
    group: "sui"
    mode: 0644

- name: Download genesis.blob
  ansible.builtin.get_url:
    url: "{{ genesis_url }}"
    dest: /opt/sui/config/genesis.blob
    owner: "sui"
    group: "sui"
    mode: 0644

- name: Stop sui-node
  systemd:
    name: sui-node
    state: stopped
  ignore_errors: yes

- name: Remove authorities directory
  file:
    state: absent
    path: "/opt/sui/db/authorities_db"
  when: reset_db == true

- name: Remove consensus directory
  file:
    state: absent
    path: "/opt/sui/db/consensus_db"
  when: reset_db == true

- name: Place binary
  ansible.builtin.get_url:
    url: "https://releases.sui.io/{{ sui_release }}/sui-node"
    dest: /opt/sui/bin/sui-node
    force: true
    mode: "0755"

- name: Copy sui-node systemd service file
  copy:
    src: "../files/sui-node.service"
    dest: /etc/systemd/system/sui-node.service
    mode: 0644
    owner: root
    group: root

- name: Reload sui-node systemd service file
  ansible.builtin.systemd:
    name: sui-node
    state: reloaded

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable sui service
  systemd:
    name: sui-node
    enabled: yes

- name: Start sui-node service
  systemd:
    name: sui-node
    state: started
  when: start_sui == true