---
- name: Include iptables tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/iptables.yaml"

- name: Include packages tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/packages.yaml"

- name: Include sysctl tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/sysctl.yaml"

- name: Include governor tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/governor.yaml"

- name: Include chronly tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/chronly.yaml"

- name: Include helpers tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/advisor.yaml"
