- name: 📦 Install additional packages
  become: yes
  apt:
    pkg:
      - update-motd
      - libssl-dev
      - libudev-dev
      - pkg-config
      - zlib1g-dev
      - llvm
      - clang
      - cmake
      - make
      - libprotobuf-dev
      - protobuf-compiler